# Generated by Django 6.0.7 on 2026-08-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_veirfied",
            field=models.BooleanField(default=False),
        ),
    ]
