# Generated by Django 6.0.7 on 2026-08-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_veirfied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_veirfied",
            new_name="is_verified",
        ),
    ]
