name: Django Project Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose build --no-cache backend

      - name: Start Containers
        run: docker compose up -d

      - name: Check Flake8
        run: docker compose exec -T backend which flake8

      - name: Run Flake8
        run: docker compose exec -T backend flake8 .

      - name: Run Tests
        run: docker compose exec -T backend pytest .
